version: '2'
services:
  dbms:
    container_name: esb_rdbms
    build: 
        context: .
        dockerfile: database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    container_name: svnrepo
    image: dockerhub.private.wso2.com/svnrepo
  manager:
    container_name: esb_manager
    depends_on: 
      - dbms
    build:
      context: .
      dockerfile: esb-manager/Dockerfile
    environment:
      - SLEEP=25
  worker1:
    container_name: esb_worker1
    depends_on: 
      - dbms
      - manager
    build:
      context: .
      dockerfile: esb-worker/Dockerfile
    environment:
      - SLEEP=50
  nginx:
    container_name: nginx
    depends_on: 
      - manager
      - worker1
    links:
      - worker1:esb.wso2.org
      - worker1:ssl.esb.wso2.org
      - manager:mgt.esb.wso2.org
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443"
      - "80:80"
